services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - ${CADDY_HTTP}
      - ${CADDY_HTTPS}
    volumes:
      - ./conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      .env

  anubis:
    image: ghcr.io/techarohq/anubis:latest
    pull_policy: always
    environment:
      BIND: ${ANUBIS_PORT}
      TARGET: ${ANUBIS_TARGET}
      POLICY_FNAME: "/data/cfg/botPolicy.yml"
    volumes:
      - "./conf/botPolicy.yml:/data/cfg/botPolicy.yml"

  static-web-server:
    build:
      dockerfile: ./conf/Containerfile
    container_name: "static-web-server"
    ports:
      - ${SWS_PORT}
    restart: unless-stopped
    environment:
      - SERVER_ROOT=${SWS_SERVER_ROOT}
      - SERVER_CONFIG_FILE=${SWS_CONFIG_FILE}
    volumes:
      - ./conf/server.toml:${SWS_CONFIG_FILE}

  php:
    container_name: status
    user: "${UID}:${GID}"
    build:
      dockerfile: ./monitor/conf/Containerfile
    volumes:
      - ./monitor/src:/var/www/html

volumes:
  caddy_data:
  caddy_config:
