FROM ghcr.io/getzola/zola:v0.20.0 as zola

ADD ./src /site-data
WORKDIR /site-data
RUN ["zola", "--config", "zola.toml", "build"]

FROM ghcr.io/static-web-server/static-web-server:latest
WORKDIR /
COPY --from=zola /site-data/public /public
COPY ./conf/server.toml /config.toml
