FROM ghcr.io/getzola/zola:v0.20.0 AS zola

USER 0
COPY ../src /build
WORKDIR /build
RUN ["zola", "--config", "zola.toml", "build"]

FROM joseluisq/static-web-server:2-alpine
WORKDIR /
COPY --from=zola /build/public /public
