#!/bin/bash

site_directory=/var/www/brandont.dev-prod
blog_submodule=$site_directory/src/content/blog
src=/var/www/brandont.dev-prod/src
scripts=/var/www/brandont.dev-prod/scripts

local_desc=$(git describe --always)
foreign_desc=$(unset $(git rev-parse --local-env-vars); git -C $site_directory/.git describe --always)

# Pull the origin main branch for the blog repo
cd $blog_submodule || exit
git --git-dir=$blog_submodule/.git pull origin main

# Pull the origin main branch for the website repo
cd $site_directory || exit
git --git-dir=$site_directory/.git pull origin main

cd /$src || exit
./"$scripts"/build-zola.sh
