#!/bin/bash

blog_root=/var/www/btp.dev/src/content/blog

unset $(git rev-parse --local-env-vars); git -C $blog_root/.git describe --always

# Pull the production main branch for the blog repo
cd $blog_root || exit
git --git-dir=$blog_root/.git pull origin main
