#!/bin/bash

site_directory=/var/www/btp.dev

unset "$(git rev-parse --local-env-vars)"; git -C $site_directory/.git describe --always

# Pull the origin main branch for the website repo
cd $site_directory || exit
git --git-dir=$site_directory/.git pull --recurse-submodules origin main

docker compose down && docker compose up --build -d
