#!/bin/bash

local_desc=$(git describe)
foreign_desc=$(unset $(git rev-parse --local-env-vars); git -C /var/www/brandont.dev-prod/content/blog/.git describe)

# Pull the production main branch for the blog repo
cd /var/www/brandont.dev-prod/content/blog || exit
git --git-dir=/var/www/brandont.dev-prod/content/blog/.git pull origin main

# Re-build the website
cd /var/www/brandont.dev-prod || exit
/usr/bin/bash /var/www/brandont.dev-prod/scripts/build-zola.sh
