#!/bin/bash

blog_root=/var/www/brandont.dev-prod/content/blog

local_desc=$(git describe)
foreign_desc=$(unset $(git rev-parse --local-env-vars); git -C $blog_root/.git describe)

# Pull the production main branch for the blog repo
cd $blog_root || exit
git --git-dir=$blog_root/.git pull origin main
